

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    eurekaServerConnectTimeoutSeconds: 60
    eurekaServerReadTimeoutSeconds: 60
  instance:
    prefer-ip-address:  true  #???????ip??????Eureka??????
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port} #??????id
    lease-expiration-duration-in-seconds: 30 #?????????????????30??
    lease-renewal-interval-in-seconds: 10 # ?????????????90??
    leaseRenewalIntervalInSeconds: 10 #???????
server:
  port: 8080
spring:
  application:
    name: security